{{- if .Values.backend.ingress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ required "You must provide a host, when enabling ingress" .Values.backend.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-backend" (include "common.names.fullname" .)) "servicePort" "http" "context" $) | nindent 14 }}
            pathType: Prefix
  tls:
    - hosts:
        - {{ required "You must provide a host, when enabling ingress" .Values.backend.ingress.host | quote }}
      secretName: {{ include "common.secrets.name" (dict "existingSecret" .Values.backend.ingress.existingCertificate "defaultNameSuffix" "custom-certificate" "context" $) }}
{{- end }}