{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "common.names.fullname" . }}-backend"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector: {{- include "common.labels.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: 80
      name: http
      targetPort: http
{{- end -}}