{{- if .Values.bot.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}-bot-data
  namespace: {{ .Release.Namespace }}
data:
  botToken: {{ required "Set the bot token at .Values.bot.token" .Values.bot.token | b64enc }}
{{- end -}}