apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "common.names.fullname" . }}-frontend"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels: {{- include "common.labels.stable" $ | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "frontend.image" . }}
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: "http://{{ include "common.names.fullname" . }}-backend.{{ .Release.Namespace }}.svc.cluster.local/"
            {{- range $k, $v := .Values.frontend.extraEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - containerPort: 4200
              name: http
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
          command: ["/bin/bash"]
          args:
            - "-c"
            - "npm start"