apiVersion: v2
description: HelmChart to deploy Goal Question Metrics System
name: gqm-system
version: 0.4.3
home: "https://gqm.darkoro.org/"
maintainers:
  - name: jpkraemer-mg
    email: j.kraemer@4allportal.com
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.19.3
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.28
    alias: postgresql
