{{- if .Values.bot.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}-mysql-data
  namespace: {{ .Release.Namespace }}
data:
  dbPass: {{ required "Set a password at .Values.mysql.leaderboard.password" .Values.mysql.leaderboard.password | b64enc }}
{{- end -}}