name: Release Charts

"on":
  push:
    branches:
      - main
    paths:
      - charts/**
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: install helm
        uses: azure/setup-helm@v4
        with:
          version: v3.5.2

      - name: install yq
        run: |
          sudo snap install yq

      - name: detect changes
        id: detect-changes
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD -- charts/*/Chart.yaml | xargs -n 1 dirname | sort -u)
          if [[ -z "$CHANGED" ]]; then
            echo "No changes"
            echo "changes=" >> $GITHUB_ENV
          else
            echo "Changes: $CHANGED"
            echo "changes=$CHANGED" >> $GITHUB_ENV
          fi

      - name: update chart dependencies
        if: env.changes
        run: |
          for DIR in $changes; do
            helm dependency update $DIR
          done

      - name: extract and add helm repos
        if: env.changes
        run: |
          for DIR in $changes; do
            FILE="$DIR/Chart.yaml"
            REPOS=$(yq e '.dependencies.[].repository' "$FILE" | sort -u)
            for REPO in $REPOS; do
              helm repo add $(basename $REPO) $REPO
            done
          done

      - name: release
        if: env.changes
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
          SKIP_EXISTING: true