name: Release Charts

"on":
  push:
    branches:
      - main
    paths:
      - charts/**
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: install helm
        uses: azure/setup-helm@v4
        with:
          version: v3.5.2

      - name: install yq
        run: |
          sudo snap install yq

      - name: update chart lock
        id: helm_deps
        run: |
          for DIR in ./charts/*; do
            CHANGED=$(git diff --name-only HEAD^ HEAD -- "$DIR")
            if [[ -z "$CHANGED" ]]; then
              continue
            fi
            helm dependency update $DIR
          done

      - name: extract and add helm repos
        id: helm-repos
        run: |
          for DIR in ./charts/*; do
            CHANGED=$(git diff --name-only HEAD^ HEAD -- "$DIR")
            if [[ -z "$CHANGED" ]]; then
              continue
            fi
            FILE="$DIR/Chart.yaml"
            DIR="${DIR//\./}"
            yq e '.dependencies.[].repository' "$FILE"
          done | sort -u | awk '{print NR " " $1}' | xargs -r -n 2 helm repo add

      - name: release
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"